export const POST_BLOG = "POST_BLOG";
export const GET_BLOG = "GET_BLOG";

// FETCH ALL BLOG POST
export const FETCH_ALL_BLOG_REQUESTING = "FETCH_ALL_BLOG_REQUESTING";
export const FETCH_ALL_BLOG_SUCCESS = "FETCH_ALL_BLOG_SUCCESS";
export const FETCH_ALL_BLOG_FAILED = "FETCH_ALL_BLOG_FAILED";
