export const COURSE_GET = "COURSE_GET";
export const COURSE_CREATE = "COURSE_CREATE";
export const COURSE_UPDATE_IN_LIST = "UPDATE_COURSE_IN_LIST";
export const COURSE_LOADING = "COURSE_LOADING";
export const COURSE_LOADED = "COURSE_LOADED";
export const COURSE_DELETE = "COURSE_DELETE";
// FETCH ALL COURSE
export const FETCH_COURSE_REQUESTING = "FETCH_COURSE_REQUESTING";
export const FETCH_MORE_COURSE_SUCCESS = "FETCH_MORE_COURSE_SUCCESS";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILED = "FETCH_COURSE_FAILED";
