export const SCHEDULE_COURSE_ONLINE_GET = "SCHEDULE_COURSE_ONLINE_GET";
export const SCHEDULE_COURSE_ONLINE_CREATE = "SCHEDULE_COURSE_ONLINE_CREATE";
export const SCHEDULE_COURSE_ONLINE_UPDATE_IN_LIST =
  "UPDATE_SCHEDULE_COURSE_ONLINE_IN_LIST";
export const SCHEDULE_COURSE_ONLINE_LOADING = "SCHEDULE_COURSE_ONLINE_LOADING";
export const SCHEDULE_COURSE_ONLINE_LOADED = "SCHEDULE_COURSE_ONLINE_LOADED";
export const SCHEDULE_COURSE_ONLINE_DELETE = "SCHEDULE_COURSE_ONLINE_DELETE";
// FETCH ALL COURSE
export const FETCH_SCHEDULE_COURSE_ONLINE_REQUESTING =
  "FETCH_SCHEDULE_COURSE_ONLINE_REQUESTING";
export const FETCH_MORE_SCHEDULE_COURSE_ONLINE_SUCCESS =
  "FETCH_MORE_SCHEDULE_COURSE_ONLINE_SUCCESS";
export const FETCH_SCHEDULE_COURSE_ONLINE_SUCCESS =
  "FETCH_SCHEDULE_COURSE_ONLINE_SUCCESS";
export const FETCH_SCHEDULE_COURSE_ONLINE_FAILED =
  "FETCH_SCHEDULE_COURSE_ONLINE_FAILED";

export const FETCH_DETAILS_SCHEDULE_COURSE_ONLINE_SUCCESS =
  "FETCH_DETAILS_SCHEDULE_COURSE_ONLINE_SUCCESS";
export const FETCH_DETAILS_SCHEDULE_COURSE_ONLINE_FAILED =
  "FETCH_DETAILS_SCHEDULE_COURSE_ONLINE_FAILED";
