export const SCHEDULE_COURSE_GET = "SCHEDULE_COURSE_GET";
export const SCHEDULE_COURSE_CREATE = "SCHEDULE_COURSE_CREATE";
export const SCHEDULE_COURSE_UPDATE_IN_LIST = "UPDATE_SCHEDULE_COURSE_IN_LIST";
export const SCHEDULE_COURSE_LOADING = "SCHEDULE_COURSE_LOADING";
export const SCHEDULE_COURSE_LOADED = "SCHEDULE_COURSE_LOADED";
export const SCHEDULE_COURSE_DELETE = "SCHEDULE_COURSE_DELETE";
// FETCH ALL COURSE
export const FETCH_SCHEDULE_COURSE_REQUESTING =
  "FETCH_SCHEDULE_COURSE_REQUESTING";
export const FETCH_MORE_SCHEDULE_COURSE_SUCCESS =
  "FETCH_MORE_SCHEDULE_COURSE_SUCCESS";
export const FETCH_SCHEDULE_COURSE_SUCCESS = "FETCH_SCHEDULE_COURSE_SUCCESS";
export const FETCH_SCHEDULE_COURSE_FAILED = "FETCH_SCHEDULE_COURSE_FAILED";
