import {
  qBank,
  qBank2,
  qBank3,
  qBank4,
  qBank5,
} from "../components/questionBank";
export const data = {
  inforUser: { name: "Trịnh Trung Kiên", age: "", gender: "" },
  inforCourse: [
    {
      title: "Tháp 1",
      totalPaid: 1000000,
      rank: 1,
      arrayVideo: [
        {
          title: "Tầng 1",
          floor: 1,
          paid: 0,
          havePermission: true,
          totalScore: 0,
          status: "paided",
          listVideo: [
            {
              id: 1,
              name: "NLP là gì? - 15p",
              url: "https://player.vimeo.com/video/897490048?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              testAt: "3111",
              question: qBank,
              score: 0,
              isVisible: true,
              floor: 1,
            },
            {
              id: 2,
              name: "Neo cảm xúc là gì? - 15p",
              url: "https://player.vimeo.com/video/901714138?h=0931e2235d&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank2,
              score: 0,
              floor: 1,
            },
            {
              id: 3,
              name: "Re-Frame là gì?",
              url: "https://player.vimeo.com/video/897488404?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank3,
              score: 0,
              floor: 1,
            },
            {
              id: 4,
              name: "Obsession là gì?",
              url: "https://player.vimeo.com/video/897488997?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank4,
              score: 0,
              floor: 1,
            },
            {
              id: 5,
              name: "Part 5",
              url: "https://player.vimeo.com/video/897487983?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank5,
              score: 0,
              floor: 1,
            },
          ],
        },
        {
          title: "Tầng 2",
          status: "",
          floor: 2,
          paid: 0,
          havePermission: false,
          totalScore: 0,
          listVideo: [
            {
              name: "30p - Video 1",
              url: "https://player.vimeo.com/video/897511310?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: true,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
            {
              name: "30p - Video 2",
              url: "https://player.vimeo.com/video/901714354?h=af4b55b6b3&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
            {
              name: "30p - Video 3",
              url: "https://player.vimeo.com/video/897524043?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
          ],
        },
      ],
    },
    {
      title: "Tháp 2",
      totalPaid: 1000000,
      status: "",
      arrayVideo: [
        {
          title: "Tầng 1",
          floor: 1,
          listVideo: [
            {
              name: "NLP là gì?",
              url: "https://vimeo.com/897490048?share=copy",
              testAt: "3111",
              question: qBank,
              score: 0,
              isVisible: true,
              floor: 1,
            },
            {
              name: "Neo cảm xúc là gì?",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 1,
            },
            {
              name: "Re-Frame là gì?",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 1,
            },
            {
              name: "Video 4",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 1,
            },
            {
              name: "Video 5",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 1,
            },
          ],
        },
        {
          title: "Tầng 2",
          floor: 2,
          listVideo: [
            {
              name: "Video 1",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
            {
              name: "Video 2",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
            {
              name: "Video 3",
              url: "https://vimeo.com/897488701?share=copy",
              isVisible: false,
              testAt: "3111",
              question: qBank,
              score: 0,
              floor: 2,
            },
          ],
        },
      ],
    },
  ],
};
